# Generated by Django 5.1.4 on 2025-01-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo', '0002_remove_order_total_price_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('ожидает обработки', 'ожидает обработки'), ('в процессе доставки', 'в процессе доставки'), ('доставлен', 'доставлен'), ('отменен', 'отменен')], default='ожидает обработки', max_length=32),
        ),
    ]
