# Generated by Django 5.1.4 on 2025-01-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo', '0003_alter_order_status_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_combos_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glovo.cartitem'),
            preserve_default=False,
        ),
    ]
